import Head from 'next/head'
import Image from 'next/image'
import acb from 'public/logo-asso/acb.png'
import cercleLogo from 'public/logo-asso/le-cercle-de-la-compliance.png'
import professionals from 'public/projet-planification.jpg'
import ACFE from '/public/logo-asso/Logo-ACFE-petit.png'
import synfie from '/public/logo-asso/logo-synfie.png'
import strategy from '/public/featuresPic/strategy.jpg'
import compliance from '/public/featuresPic/compliance.jpg'
import operationnal from '/public/featuresPic/operationnal.jpg'

import drapeaux from '/public/drapeaux-ue.jpg'
import logo from '/public/logo-celtic.png'
import MapChart from "@/pages/Component/Map";
import React, {useState} from "react";
import Link from "next/link";


export default function Home() {
    const [openTab, setOpenTab] = useState(1);

    return (
        <>
            <Head>
                <title>Celtics Intelligence</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/logo-celtic.png"/>
            </Head>
            <main>
                <div className="flex flex-col items-center justify-center min-h-screen ">
                    <div
                        className="absolute backdrop-blur-sm top-0 left-0 w-full h-screen p-6"
                        style={{
                            backgroundImage: "url('/buildings.jpg')",
                            backgroundSize: "cover",
                            backgroundPosition: "center",
                        }}
                    >

                    </div>
                    <div
                        className="relative z-10 flex flex-col gap-1 items-center justify-center  px-4 py-8 rounded-md s">
                        <div className={"flex gap-2"}>
                            <Image src={logo} alt={"logo"} width={40} height={40}/>
                            <h1 className="text-4xl font-bold text-white"> Celtics-intelligence</h1>
                        </div>
                        <h2 className={"text-2xl font-semibold text-white"}>TRANSVERSAL INVESTIGATIONS & ANALYSES</h2>
                    </div>
                </div>
                <section className="bg-white dark:bg-gray-900">
                    <div className="py-8 px-4 mx-auto max-w-screen-xl text-center lg:py-16 lg:px-12">

                        <div
                            className="gap-8 items-center py-8 px-4 mx-auto max-w-screen-xl xl:gap-16 md:grid md:grid-cols-2 sm:py-16 lg:px-6">
                            <Image src={drapeaux} alt={"Flags of UE"} className={"rounded-2xl"}/>

                            <div className="mt-4 md:mt-0">
                                <h2 className="mb-4 text-5xl tracking-tight font-bold text-gray-900 dark:text-white">Transform
                                    Your Business with Our Economic Intelligence Solutions.</h2>
                                <p className="mb-6  text-gray-500 sm:text-xl  dark:text-gray-400">Celtic Intelligence is
                                    an Ireland-based, leaded by an experimented French citizen, consultancy
                                    that services exclusively European clients base providing corporate investigations,
                                    market
                                    intelligence, political risk assessments and advisory services.
                                </p>
                                <Link className="inline-flex justify-center items-center gap-x-3 text-center bg-primary hover:bg-primary/80 border border-transparent text-white text-sm font-medium rounded-md focus:outline-none focus:ring-2 focus:ring-blue-600 focus:ring-offset-2 focus:ring-offset-white transition py-3 px-4 dark:focus:ring-offset-gray-800"
                                   href="/contact">
                                    Contact Us
                                    <svg className="w-3 h-3" width="16" height="16" viewBox="0 0 16 16" fill="none">
                                        <path
                                            d="M5.27921 2L10.9257 7.64645C11.1209 7.84171 11.1209 8.15829 10.9257 8.35355L5.27921 14"
                                            stroke="currentColor" stroke-width="2" stroke-linecap="round"/>
                                    </svg>
                                </Link>
                            </div>
                        </div>

                    </div>
                </section>
                <div className=" px-24 py-5 mx-auto text-center bg-blue-50/30">
                    <span className="font-semibold text-gray-400 uppercase">TRUSTED BY PROFESSIONAL</span>
                    {/*Professionals*/}
                    <div
                        className="flex flex-wrap justify-center items-center mt-8 text-gray-500 sm:justify-between">
                        <a href="#" className="mr-5 mb-5 lg:mb-0 hover:text-gray-800 dark:hover:text-gray-400">
                            <Image src={acb} alt={"logo acb"} width={200}
                                   className={"grayscale hover:grayscale-0"}/>
                        </a>
                        <a href="#" className="mr-5 mb-5 lg:mb-0 hover:text-gray-800 dark:hover:text-gray-400">
                            <Image src={cercleLogo} alt={"logo acb"} height={100}
                                   className={"grayscale hover:grayscale-0"}/>
                        </a>
                        <a href="#" className="mr-5 mb-5 lg:mb-0 hover:text-gray-800 dark:hover:text-gray-400">
                            <Image src={ACFE} alt={"logo acb"} height={100} width={200}
                                   className={"grayscale hover:grayscale-0"}/>
                        </a>
                        <a href="#" className="mr-5 mb-5 lg:mb-0 hover:text-gray-800 dark:hover:text-gray-400">
                            <Image src={synfie} alt={"logo acb"} height={100} width={200}
                                   className={"grayscale hover:grayscale-0"}/>
                        </a>
                    </div>
                    {/* fin professional*/}
                </div>
                {/*Content sectction*/}
                <section
                    className="relative isolate overflow-hidden bg-white px-6 py-24 sm:py-32 lg:overflow-visible lg:px-0">

                    <div
                        className="mx-auto grid max-w-2xl grid-cols-1 gap-x-8  lg:mx-0 lg:max-w-none lg:grid-cols-2 lg:items-start ">
                        <div
                            className="lg:col-span-2 lg:col-start-1 lg:row-start-1 lg:mx-auto lg:grid lg:w-full lg:max-w-7xl lg:grid-cols-2 lg:gap-x-8 lg:px-8">
                            <div className="lg:pr-4">
                                <div className="lg:max-w-lg">
                                    <p className="text-base font-semibold leading-7 text-primary">Go worldwide</p>
                                    <h1 className="mt-2 text-3xl font-bold tracking-tight text-gray-900 sm:text-4xl">Strong
                                        links to key markets</h1>
                                    <p className="mt-6 text-xl leading-8 text-gray-700">Global Reach, Local Expertise:
                                        Our Network Across Africa, Europe, Middle East, and Latin America</p>
                                </div>
                            </div>
                        </div>
                        <div
                            className="-ml-12 -mt-12 p-12 lg:sticky lg:top-4 lg:col-start-2 lg:row-span-2 lg:row-start-1 lg:overflow-hidden">
                            <MapChart/>
                        </div>
                        <div
                            className="lg:col-span-2 lg:col-start-1 lg:row-start-2 lg:mx-auto lg:grid lg:w-full lg:max-w-7xl lg:grid-cols-2 lg:gap-x-8 lg:px-8">
                            <div className="lg:pr-4">
                                <div className="max-w-xl text-base leading-7 text-gray-700 lg:max-w-lg">
                                    <p>We have an expansive global network across multiple regions.</p>
                                    <ul role="list" className="mt-8 space-y-8 text-gray-600">
                                        <li className="flex gap-x-3">
                                            <svg
                                                className="flex-shrink-0 h-6 w-6 text-blue-600 dark:text-blue-500"
                                                width={16}
                                                height={16}
                                                viewBox="0 0 16 16"
                                                fill="none"
                                                xmlns="http://www.w3.org/2000/svg"
                                            >
                                                <path
                                                    d="M15.1965 7.85999C15.1965 3.71785 11.8387 0.359985 7.69653 0.359985C3.5544 0.359985 0.196533 3.71785 0.196533 7.85999C0.196533 12.0021 3.5544 15.36 7.69653 15.36C11.8387 15.36 15.1965 12.0021 15.1965 7.85999Z"
                                                    fill="currentColor"
                                                    fillOpacity="0.1"
                                                />
                                                <path
                                                    d="M10.9295 4.88618C11.1083 4.67577 11.4238 4.65019 11.6343 4.82904C11.8446 5.00788 11.8702 5.32343 11.6914 5.53383L7.44139 10.5338C7.25974 10.7475 6.93787 10.77 6.72825 10.5837L4.47825 8.5837C4.27186 8.40024 4.25327 8.0842 4.43673 7.87781C4.62019 7.67142 4.93622 7.65283 5.14261 7.83629L7.01053 9.49669L10.9295 4.88618Z"
                                                    fill="currentColor"
                                                />
                                            </svg>
                                            <span><strong
                                                className="font-semibold text-lg text-gray-900">Africa</strong>   </span>
                                        </li>
                                        <li className="flex gap-x-3">
                                            <svg
                                                className="flex-shrink-0 h-6 w-6 text-blue-600 dark:text-blue-500"
                                                width={16}
                                                height={16}
                                                viewBox="0 0 16 16"
                                                fill="none"
                                                xmlns="http://www.w3.org/2000/svg"
                                            >
                                                <path
                                                    d="M15.1965 7.85999C15.1965 3.71785 11.8387 0.359985 7.69653 0.359985C3.5544 0.359985 0.196533 3.71785 0.196533 7.85999C0.196533 12.0021 3.5544 15.36 7.69653 15.36C11.8387 15.36 15.1965 12.0021 15.1965 7.85999Z"
                                                    fill="currentColor"
                                                    fillOpacity="0.1"
                                                />
                                                <path
                                                    d="M10.9295 4.88618C11.1083 4.67577 11.4238 4.65019 11.6343 4.82904C11.8446 5.00788 11.8702 5.32343 11.6914 5.53383L7.44139 10.5338C7.25974 10.7475 6.93787 10.77 6.72825 10.5837L4.47825 8.5837C4.27186 8.40024 4.25327 8.0842 4.43673 7.87781C4.62019 7.67142 4.93622 7.65283 5.14261 7.83629L7.01053 9.49669L10.9295 4.88618Z"
                                                    fill="currentColor"
                                                />
                                            </svg>
                                            <span><strong className="font-semibold text-lg text-gray-900">Middle East and Gulf area,</strong></span>
                                        </li>
                                        <li className="flex gap-x-3">
                                            <svg
                                                className="flex-shrink-0 h-6 w-6 text-blue-600 dark:text-blue-500"
                                                width={16}
                                                height={16}
                                                viewBox="0 0 16 16"
                                                fill="none"
                                                xmlns="http://www.w3.org/2000/svg"
                                            >
                                                <path
                                                    d="M15.1965 7.85999C15.1965 3.71785 11.8387 0.359985 7.69653 0.359985C3.5544 0.359985 0.196533 3.71785 0.196533 7.85999C0.196533 12.0021 3.5544 15.36 7.69653 15.36C11.8387 15.36 15.1965 12.0021 15.1965 7.85999Z"
                                                    fill="currentColor"
                                                    fillOpacity="0.1"
                                                />
                                                <path
                                                    d="M10.9295 4.88618C11.1083 4.67577 11.4238 4.65019 11.6343 4.82904C11.8446 5.00788 11.8702 5.32343 11.6914 5.53383L7.44139 10.5338C7.25974 10.7475 6.93787 10.77 6.72825 10.5837L4.47825 8.5837C4.27186 8.40024 4.25327 8.0842 4.43673 7.87781C4.62019 7.67142 4.93622 7.65283 5.14261 7.83629L7.01053 9.49669L10.9295 4.88618Z"
                                                    fill="currentColor"
                                                />
                                            </svg>
                                            <span><strong className="font-semibold text-lg text-gray-900">Western and Central Europe</strong></span>
                                        </li>
                                        <li className="flex gap-x-3">
                                            <svg
                                                className="flex-shrink-0 h-6 w-6 text-blue-600 dark:text-blue-500"
                                                width={16}
                                                height={16}
                                                viewBox="0 0 16 16"
                                                fill="none"
                                                xmlns="http://www.w3.org/2000/svg"
                                            >
                                                <path
                                                    d="M15.1965 7.85999C15.1965 3.71785 11.8387 0.359985 7.69653 0.359985C3.5544 0.359985 0.196533 3.71785 0.196533 7.85999C0.196533 12.0021 3.5544 15.36 7.69653 15.36C11.8387 15.36 15.1965 12.0021 15.1965 7.85999Z"
                                                    fill="currentColor"
                                                    fillOpacity="0.1"
                                                />
                                                <path
                                                    d="M10.9295 4.88618C11.1083 4.67577 11.4238 4.65019 11.6343 4.82904C11.8446 5.00788 11.8702 5.32343 11.6914 5.53383L7.44139 10.5338C7.25974 10.7475 6.93787 10.77 6.72825 10.5837L4.47825 8.5837C4.27186 8.40024 4.25327 8.0842 4.43673 7.87781C4.62019 7.67142 4.93622 7.65283 5.14261 7.83629L7.01053 9.49669L10.9295 4.88618Z"
                                                    fill="currentColor"
                                                />
                                            </svg>
                                            <span><strong
                                                className="font-semibold text-xl text-gray-900">Latin America</strong></span>
                                        </li>
                                    </ul>

                                </div>
                            </div>
                        </div>
                    </div>
                </section>


                <section className="  dark:bg-gray-900">

                    {/* Features */}
                    <div className="max-w-[85rem] px-4 py-10 sm:px-6 lg:px-8 lg:py-14 mx-auto">
                        <div className="relative p-6 md:p-16">
                            {/* Grid */}
                            <div className="relative z-10 lg:grid lg:grid-cols-12 lg:gap-16 lg:items-center">
                                <div className="mb-10 lg:mb-0 lg:col-span-6 lg:col-start-8 lg:order-2">
                                    <h2 className="text-2xl text-gray-800 font-bold sm:text-3xl dark:text-gray-200">
                                        Our area of expertise
                                    </h2>
                                    <p className="text-gray-500 text-md  dark:text-gray-400 text-left">Our expertise in economic intelligence covers key areas of strategy,
                                        compliance, and operations. We offer sector studies, background checks, due diligence,
                                        as well as support for compliance, including anti-corruption accompaniment and export assistance..
                                    </p>
                                    {/* Tab Navs */}
                                    <nav className="grid gap-4 mt-5 md:mt-10" aria-label="Tabs" role="tablist">
                                        <button type="button"
                                                onClick={e => {
                                                    e.preventDefault();
                                                    setOpenTab(1);
                                                }}
                                                className={" text-left " +
                                                    " p-4 md:p-5 rounded-xl  " +
                                                    (openTab === 1
                                                        ? "bg-white shadow-md   dark:bg-slate-900"
                                                        : "hover:bg-gray-200 dark:hover:bg-gray-700")
                                                }
                                                 id="tabs-with-card-item-1" data-hs-tab="#tabs-with-card-1"
                                                aria-controls="tabs-with-card-1" role="tab">
             <span className="flex">
             <svg
                 className={"flex-shrink-0 mt-2 h-6 w-6 md:w-7 md:h-7  " +(openTab === 1
                     ? "text-lightPrimary dark:text-blue-500 "
                     : "text-gray-800 dark:text-gray-200")
                 }
                 xmlns="http://www.w3.org/2000/svg" width={16} height={16} fill="currentColor" viewBox="0 0 16 16">
             <path
                 d="M5.5 2A3.5 3.5 0 0 0 2 5.5v5A3.5 3.5 0 0 0 5.5 14h5a3.5 3.5 0 0 0 3.5-3.5V8a.5.5 0 0 1 1 0v2.5a4.5 4.5 0 0 1-4.5 4.5h-5A4.5 4.5 0 0 1 1 10.5v-5A4.5 4.5 0 0 1 5.5 1H8a.5.5 0 0 1 0 1H5.5z"/>
             <path d="M16 3a3 3 0 1 1-6 0 3 3 0 0 1 6 0z"/>
             </svg>
             <span className="grow ml-6">
             <span
                 className={"block text-lg font-semibold  "+(openTab === 1
                     ? "text-lightPrimary dark:text-blue-500 "
                     : "text-gray-800 dark:text-gray-200")}>Strategy</span>
             <span className="block mt-1 text-gray-800 dark:hs-tab-active:text-gray-200 dark:text-gray-200"> Sector studies & Business Intelligence Mapping</span>
             </span>
             </span>
                                        </button>
                                        <button type="button"
                                                onClick={e => {
                                                    e.preventDefault();
                                                    setOpenTab(2);
                                                }}
                                                className={" text-left p-4 md:p-5 rounded-xl  " +
                                            (openTab === 2
                                                ? "bg-white shadow-md   dark:bg-slate-900"
                                                : "hover:bg-gray-200 dark:hover:bg-gray-700")
                                        }
                                                id="tabs-with-card-item-2" data-hs-tab="#tabs-with-card-2"
                                                aria-controls="tabs-with-card-2" role="tab">
             <span className="flex">
             <svg
                 className={"flex-shrink-0 mt-2 h-6 w-6 md:w-7 md:h-7  " +(openTab === 2
                     ? "text-lightPrimary dark:text-blue-500 "
                     : "text-gray-800 dark:text-gray-200")
                 }
                 xmlns="http://www.w3.org/2000/svg" width={16} height={16} fill="currentColor" viewBox="0 0 16 16">
             <path fillRule="evenodd"
                   d="M0 0h1v15h15v1H0V0Zm14.817 3.113a.5.5 0 0 1 .07.704l-4.5 5.5a.5.5 0 0 1-.74.037L7.06 6.767l-3.656 5.027a.5.5 0 0 1-.808-.588l4-5.5a.5.5 0 0 1 .758-.06l2.609 2.61 4.15-5.073a.5.5 0 0 1 .704-.07Z"/>
             </svg>
             <span className="grow ml-6">
             <span
                 className={"block text-lg font-semibold  "+(openTab === 2
                     ? "text-lightPrimary dark:text-blue-500 "
                     : "text-gray-800 dark:text-gray-200")}>Compliance</span>
             <span className="block mt-1 text-gray-800 dark:hs-tab-active:text-gray-200 dark:text-gray-200">Background background checks
• Due diligence
• Support for compliance</span>
             </span>
             </span>
                                        </button>
                                        <button type="button"
                                                onClick={e => {
                                                    e.preventDefault();
                                                    setOpenTab(3);
                                                }}
                                                className={" text-left " +
                                                    " p-4 md:p-5 rounded-xl  " +
                                                        (openTab === 3
                                                            ? "bg-white shadow-md   dark:bg-slate-900"
                                                            : "hover:bg-gray-200 dark:hover:bg-gray-700")
                                                }
                                                id="tabs-with-card-item-3" data-hs-tab="#tabs-with-card-3"
                                                aria-controls="tabs-with-card-3" role="tab">
             <span className="flex">
             <svg
                 className={"flex-shrink-0 mt-2 h-6 w-6 md:w-7 md:h-7  " +(openTab === 3
                     ? "text-lightPrimary dark:text-blue-500 "
                     : "text-gray-800 dark:text-gray-200")
                 }
                 xmlns="http://www.w3.org/2000/svg" width={16} height={16} fill="currentColor" viewBox="0 0 16 16">
             <path
                 d="M5.52.359A.5.5 0 0 1 6 0h4a.5.5 0 0 1 .474.658L8.694 6H12.5a.5.5 0 0 1 .395.807l-7 9a.5.5 0 0 1-.873-.454L6.823 9.5H3.5a.5.5 0 0 1-.48-.641l2.5-8.5zM6.374 1 4.168 8.5H7.5a.5.5 0 0 1 .478.647L6.78 13.04 11.478 7H8a.5.5 0 0 1-.474-.658L9.306 1H6.374z"/>
             </svg>
             <span className="grow ml-6">
             <span
                 className={"block text-lg font-semibold  "+(openTab === 3
                     ? "text-lightPrimary dark:text-blue-500 "
                     : "text-gray-800 dark:text-gray-200")}>Operationnal</span>

             <span className="block mt-1 text-gray-800 dark:hs-tab-active:text-gray-200 dark:text-gray-200">• Accompaniment anti-corruption
• Export support</span>
             </span>
             </span>
                                        </button>
                                    </nav>
                                    {/* End Tab Navs */}
                                </div>
                                {/* End Col */}
                                <div className="lg:col-span-6">
                                    <div className="relative">
                                        {/* Tab Content */}
                                        <div>
                                            {
                                                (() => {
                                                    switch (openTab) {
                                                        case 1:
                                                            return (
                                                                <div
                                                                    id="tabs-with-card-1"
                                                                    role="tabpanel"
                                                                    aria-labelledby="tabs-with-card-item-1"
                                                                >
                                                                    <Image
                                                                        className="shadow-xl shadow-gray-200 rounded-xl dark:shadow-gray-900/[.2]"
                                                                        src={strategy}
                                                                        alt="Team establishing a strategy"
                                                                        width={987}


                                                                    />
                                                                </div>
                                                            );
                                                        case 2:
                                                            return (
                                                                <div
                                                                    id="tabs-with-card-2"
                                                                    role="tabpanel"
                                                                    aria-labelledby="tabs-with-card-item-2"
                                                                >
                                                                    <Image
                                                                        className="shadow-xl shadow-gray-200 rounded-xl dark:shadow-gray-900/[.2]"
                                                                        src={compliance}
                                                                        alt="Important contract"
                                                                        width={987}
                                                                    />
                                                                </div>
                                                            );
                                                        case 3:
                                                            return (
                                                                <div
                                                                    id="tabs-with-card-3"
                                                                    role="tabpanel"
                                                                    aria-labelledby="tabs-with-card-item-3"
                                                                >
                                                                    <Image
                                                                        className="shadow-xl shadow-gray-200 rounded-xl dark:shadow-gray-900/[.2]"
                                                                        src={operationnal}
                                                                        alt="Woman talking to people"
                                                                        width={987}
                                                                        height={1220}
                                                                    />
                                                                </div>
                                                            );
                                                            //DEfaut
                                                        default:
                                                            return null;
                                                    }
                                                })()
                                            }
                                        </div>
                                        {/* End Tab Content */}

                                    </div>
                                </div>
                                {/* End Col */}
                            </div>
                            {/* End Grid */}
                            {/* Background Color */}
                            <div className="absolute inset-0 grid grid-cols-12 w-full h-full">
                                <div
                                    className="col-span-full lg:col-span-7 lg:col-start-6 bg-blue-50/30 w-full h-5/6 rounded-xl sm:h-3/4 lg:h-full dark:bg-white/[.075]"/>
                            </div>
                            {/* End Background Color */}
                        </div>
                    </div>
                    {/* End Features */}
                </section>
                <section>

                    <div className="py-16">
                        <div className="xl:container m-auto px-6 text-gray-600 md:px-12 xl:px-16">
                            <div
                                className="lg:bg-blue-50/30 dark:lg:bg-darker lg:p-16 rounded-[4rem] space-y-6 md:flex flex-row-reverse md:gap-6 justify-center md:space-y-0 lg:items-center">
                                <div className="md:5/12 lg:w-1/2">
                                    <Image src={professionals} alt={"Team"} className={"rounded-xl"}/>

                                </div>
                                <div className="md:7/12 lg:w-1/2">
                                    <h2 className="text-3xl font-bold text-gray-900 md:text-4xl dark:text-white">
                                        Professionals dedicated to your success
                                    </h2>
                                    <p className="my-8 text-gray-600 dark:text-gray-300">
                                        Our team is skilled, experienced and discreet, allowing us to work closely
                                        with clients to mitigate risks and make informed decisions in challenging
                                        and complex business environments.
                                    </p>
                                </div>
                            </div>
                        </div>
                    </div>
                </section>
            </main>
        </>
    )
}
