import Head from 'next/head'
import Image from 'next/image'
import acb from 'public/logo-asso/acb.png'
import cercleLogo from 'public/logo-asso/le-cercle-de-la-compliance.png'
import professionals from 'public/projet-planification.jpg'
import ACFE from '/public/logo-asso/Logo-ACFE-petit.png'
import synfie from '/public/logo-asso/logo-synfie.png'
import strategy from '/public/featuresPic/strategy.jpg'
import compliance from '/public/featuresPic/compliance.jpg'
import operationnal from '/public/featuresPic/operationnal.jpg'

import drapeaux from '/public/drapeaux-ue.jpg'
import logo from '/public/logo-celtic.png'
import MapChart from "@/pages/Component/Map";
import React, {useState} from "react";


export default function Home() {
    const [openTab, setOpenTab] = useState(1);

    return (
        <>
            <Head>
                <title>Celtics Intelligence</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/logo-celtic.png"/>
            </Head>
            <main>
                <div className="flex flex-col items-center justify-center min-h-screen ">
                    <div
                        className="absolute backdrop-blur-sm top-0 left-0 w-full h-screen p-6"
                        style={{
                            backgroundImage: "url('/buildings.jpg')",
                            backgroundSize: "cover",
                            backgroundPosition: "center",
                        }}
                    >

                    </div>
                    <div
                        className="relative z-10 flex flex-col gap-1 items-center justify-center  px-4 py-8 rounded-md s">
                        <div className={"flex gap-2"}>
                            <Image src={logo} alt={"logo"} width={40} height={40}/>
                            <h1 className="text-4xl font-bold text-white"> Celtics-intelligence</h1>
                        </div>
                        <h2 className={"text-2xl font-semibold text-white"}>TRANSVERSAL INVESTIGATIONS & ANALYSES</h2>
                    </div>
                </div>
                <section className="bg-white dark:bg-gray-900">
                    <div className="py-8 px-4 mx-auto max-w-screen-xl text-center lg:py-16 lg:px-12">

                        <div
                            className="gap-8 items-center py-8 px-4 mx-auto max-w-screen-xl xl:gap-16 md:grid md:grid-cols-2 sm:py-16 lg:px-6">
                            <Image src={drapeaux} alt={"Flags of UE"} className={"rounded-2xl"}/>

                            <div className="mt-4 md:mt-0">
                                <h2 className="mb-4 text-4xl tracking-tight font-extrabold text-gray-900 dark:text-white">Transform
                                    Your Business with Our Economic Intelligence Solutions.</h2>
                                <p className="mb-6  text-gray-500 sm:text-xl  dark:text-gray-400">Celtic Intelligence is
                                    an Ireland-based, leaded by an experimented French citizen, consultancy
                                    that services exclusively European clients base providing corporate investigations,
                                    market
                                    intelligence, political risk assessments and advisory services.
                                </p>
                                <a className="inline-flex justify-center items-center gap-x-3 text-center bg-primary hover:bg-primary/80 border border-transparent text-white text-sm font-medium rounded-md focus:outline-none focus:ring-2 focus:ring-blue-600 focus:ring-offset-2 focus:ring-offset-white transition py-3 px-4 dark:focus:ring-offset-gray-800"
                                   href="">
                                    Contact Us
                                    <svg className="w-3 h-3" width="16" height="16" viewBox="0 0 16 16" fill="none">
                                        <path
                                            d="M5.27921 2L10.9257 7.64645C11.1209 7.84171 11.1209 8.15829 10.9257 8.35355L5.27921 14"
                                            stroke="currentColor" stroke-width="2" stroke-linecap="round"/>
                                    </svg>
                                </a>
                            </div>
                        </div>
                        <div className="px-4 mx-auto text-center">
                            <span className="font-semibold text-gray-400 uppercase">TRUSTED BY PROFESSIONAL</span>
                            {/*Professionals*/}
                            <div
                                className="flex flex-wrap justify-center items-center mt-8 text-gray-500 sm:justify-between">
                                <a href="#" className="mr-5 mb-5 lg:mb-0 hover:text-gray-800 dark:hover:text-gray-400">
                                    <Image src={acb} alt={"logo acb"} width={200}
                                           className={"grayscale hover:grayscale-0"}/>
                                </a>
                                <a href="#" className="mr-5 mb-5 lg:mb-0 hover:text-gray-800 dark:hover:text-gray-400">
                                    <Image src={cercleLogo} alt={"logo acb"} height={100}
                                           className={"grayscale hover:grayscale-0"}/>
                                </a>
                                <a href="#" className="mr-5 mb-5 lg:mb-0 hover:text-gray-800 dark:hover:text-gray-400">
                                    <Image src={ACFE} alt={"logo acb"} height={100} width={200}
                                           className={"grayscale hover:grayscale-0"}/>
                                </a>
                                <a href="#" className="mr-5 mb-5 lg:mb-0 hover:text-gray-800 dark:hover:text-gray-400">
                                    <Image src={synfie} alt={"logo acb"} height={100} width={200}
                                           className={"grayscale hover:grayscale-0"}/>
                                </a>
                            </div>
                            {/* fin professional*/}
                        </div>
                    </div>
                </section>
                {/*Content sectction*/}
                <section
                    className="relative isolate overflow-hidden bg-white px-6 py-24 sm:py-32 lg:overflow-visible lg:px-0">

                    <div
                        className="mx-auto grid max-w-2xl grid-cols-1 gap-x-8  lg:mx-0 lg:max-w-none lg:grid-cols-2 lg:items-start ">
                        <div
                            className="lg:col-span-2 lg:col-start-1 lg:row-start-1 lg:mx-auto lg:grid lg:w-full lg:max-w-7xl lg:grid-cols-2 lg:gap-x-8 lg:px-8">
                            <div className="lg:pr-4">
                                <div className="lg:max-w-lg">
                                    <p className="text-base font-semibold leading-7 text-primary">Go worldwide</p>
                                    <h1 className="mt-2 text-3xl font-bold tracking-tight text-gray-900 sm:text-4xl">Strong
                                        links to key markets</h1>
                                    <p className="mt-6 text-xl leading-8 text-gray-700">Global Reach, Local Expertise:
                                        Our Network Across Africa, Europe, Middle East, and Latin America</p>
                                </div>
                            </div>
                        </div>
                        <div
                            className="-ml-12 -mt-12 p-12 lg:sticky lg:top-4 lg:col-start-2 lg:row-span-2 lg:row-start-1 lg:overflow-hidden">
                            <MapChart/>
                        </div>
                        <div
                            className="lg:col-span-2 lg:col-start-1 lg:row-start-2 lg:mx-auto lg:grid lg:w-full lg:max-w-7xl lg:grid-cols-2 lg:gap-x-8 lg:px-8">
                            <div className="lg:pr-4">
                                <div className="max-w-xl text-base leading-7 text-gray-700 lg:max-w-lg">
                                    <p>We have an expansive global network across multiple regions.</p>
                                    <ul role="list" className="mt-8 space-y-8 text-gray-600">
                                        <li className="flex gap-x-3">
                                            <svg className="mt-1 h-5 w-5 flex-none text-primary" viewBox="0 0 20 20"
                                                 fill="currentColor" aria-hidden="true">
                                                <path fill-rule="evenodd"
                                                      d="M5.5 17a4.5 4.5 0 01-1.44-8.765 4.5 4.5 0 018.302-3.046 3.5 3.5 0 014.504 4.272A4 4 0 0115 17H5.5zm3.75-2.75a.75.75 0 001.5 0V9.66l1.95 2.1a.75.75 0 101.1-1.02l-3.25-3.5a.75.75 0 00-1.1 0l-3.25 3.5a.75.75 0 101.1 1.02l1.95-2.1v4.59z"
                                                      clip-rule="evenodd"/>
                                            </svg>
                                            <span><strong
                                                className="font-semibold text-lg text-gray-900">Africa</strong>   </span>
                                        </li>
                                        <li className="flex gap-x-3">
                                            <svg className="mt-1 h-5 w-5 flex-none text-primary" viewBox="0 0 20 20"
                                                 fill="currentColor" aria-hidden="true">
                                                <path fill-rule="evenodd"
                                                      d="M10 1a4.5 4.5 0 00-4.5 4.5V9H5a2 2 0 00-2 2v6a2 2 0 002 2h10a2 2 0 002-2v-6a2 2 0 00-2-2h-.5V5.5A4.5 4.5 0 0010 1zm3 8V5.5a3 3 0 10-6 0V9h6z"
                                                      clip-rule="evenodd"/>
                                            </svg>
                                            <span><strong className="font-semibold text-lg text-gray-900">Middle East and Gulf area,</strong></span>
                                        </li>
                                        <li className="flex gap-x-3">
                                            <svg className="mt-1 h-5 w-5 flex-none text-primary" viewBox="0 0 20 20"
                                                 fill="currentColor" aria-hidden="true">
                                                <path
                                                    d="M4.632 3.533A2 2 0 016.577 2h6.846a2 2 0 011.945 1.533l1.976 8.234A3.489 3.489 0 0016 11.5H4c-.476 0-.93.095-1.344.267l1.976-8.234z"/>
                                                <path fill-rule="evenodd"
                                                      d="M4 13a2 2 0 100 4h12a2 2 0 100-4H4zm11.24 2a.75.75 0 01.75-.75H16a.75.75 0 01.75.75v.01a.75.75 0 01-.75.75h-.01a.75.75 0 01-.75-.75V15zm-2.25-.75a.75.75 0 00-.75.75v.01c0 .414.336.75.75.75H13a.75.75 0 00.75-.75V15a.75.75 0 00-.75-.75h-.01z"
                                                      clip-rule="evenodd"/>
                                            </svg>
                                            <span><strong className="font-semibold text-lg text-gray-900">Western and Central Europe</strong></span>
                                        </li>
                                        <li className="flex gap-x-3">
                                            <svg className="mt-1 h-5 w-5 flex-none text-primary" viewBox="0 0 20 20"
                                                 fill="currentColor" aria-hidden="true">
                                                <path
                                                    d="M4.632 3.533A2 2 0 016.577 2h6.846a2 2 0 011.945 1.533l1.976 8.234A3.489 3.489 0 0016 11.5H4c-.476 0-.93.095-1.344.267l1.976-8.234z"/>
                                                <path fill-rule="evenodd"
                                                      d="M4 13a2 2 0 100 4h12a2 2 0 100-4H4zm11.24 2a.75.75 0 01.75-.75H16a.75.75 0 01.75.75v.01a.75.75 0 01-.75.75h-.01a.75.75 0 01-.75-.75V15zm-2.25-.75a.75.75 0 00-.75.75v.01c0 .414.336.75.75.75H13a.75.75 0 00.75-.75V15a.75.75 0 00-.75-.75h-.01z"
                                                      clip-rule="evenodd"/>
                                            </svg>
                                            <span><strong
                                                className="font-semibold text-xl text-gray-900">Latin America</strong></span>
                                        </li>
                                    </ul>

                                </div>
                            </div>
                        </div>
                    </div>
                </section>


                <section className="  dark:bg-gray-900">

                    {/* Features */}
                    <div className="max-w-[85rem] px-4 py-10 sm:px-6 lg:px-8 lg:py-14 mx-auto">
                        <div className="relative p-6 md:p-16">
                            {/* Grid */}
                            <div className="relative z-10 lg:grid lg:grid-cols-12 lg:gap-16 lg:items-center">
                                <div className="mb-10 lg:mb-0 lg:col-span-6 lg:col-start-8 lg:order-2">
                                    <h2 className="text-2xl text-gray-800 font-bold sm:text-3xl dark:text-gray-200">
                                        Our area of expertise
                                    </h2>
                                    <p className="text-gray-500 text-md  dark:text-gray-400 text-left">Our expertise in economic intelligence covers key areas of strategy,
                                        compliance, and operations. We offer sector studies, background checks, due diligence,
                                        as well as support for compliance, including anti-corruption accompaniment and export assistance..
                                    </p>
                                    {/* Tab Navs */}
                                    <nav className="grid gap-4 mt-5 md:mt-10" aria-label="Tabs" role="tablist">
                                        <button type="button"
                                                onClick={e => {
                                                    e.preventDefault();
                                                    setOpenTab(1);
                                                }}
                                                className={" text-left " +
                                                    " p-4 md:p-5 rounded-xl  " +
                                                    (openTab === 1
                                                        ? "bg-white shadow-md   dark:bg-slate-900"
                                                        : "hover:bg-gray-200 dark:hover:bg-gray-700")
                                                }
                                                 id="tabs-with-card-item-1" data-hs-tab="#tabs-with-card-1"
                                                aria-controls="tabs-with-card-1" role="tab">
             <span className="flex">
             <svg
                 className={"flex-shrink-0 mt-2 h-6 w-6 md:w-7 md:h-7  " +(openTab === 1
                     ? "text-lightPrimary dark:text-blue-500 "
                     : "text-gray-800 dark:text-gray-200")
                 }
                 xmlns="http://www.w3.org/2000/svg" width={16} height={16} fill="currentColor" viewBox="0 0 16 16">
             <path
                 d="M5.5 2A3.5 3.5 0 0 0 2 5.5v5A3.5 3.5 0 0 0 5.5 14h5a3.5 3.5 0 0 0 3.5-3.5V8a.5.5 0 0 1 1 0v2.5a4.5 4.5 0 0 1-4.5 4.5h-5A4.5 4.5 0 0 1 1 10.5v-5A4.5 4.5 0 0 1 5.5 1H8a.5.5 0 0 1 0 1H5.5z"/>
             <path d="M16 3a3 3 0 1 1-6 0 3 3 0 0 1 6 0z"/>
             </svg>
             <span className="grow ml-6">
             <span
                 className={"block text-lg font-semibold  "+(openTab === 1
                     ? "text-lightPrimary dark:text-blue-500 "
                     : "text-gray-800 dark:text-gray-200")}>Strategy</span>
             <span className="block mt-1 text-gray-800 dark:hs-tab-active:text-gray-200 dark:text-gray-200"> Sector studies & Business Intelligence Mapping</span>
             </span>
             </span>
                                        </button>
                                        <button type="button"
                                                onClick={e => {
                                                    e.preventDefault();
                                                    setOpenTab(2);
                                                }}
                                                className={" text-left p-4 md:p-5 rounded-xl  " +
                                            (openTab === 2
                                                ? "bg-white shadow-md   dark:bg-slate-900"
                                                : "hover:bg-gray-200 dark:hover:bg-gray-700")
                                        }
                                                id="tabs-with-card-item-2" data-hs-tab="#tabs-with-card-2"
                                                aria-controls="tabs-with-card-2" role="tab">
             <span className="flex">
             <svg
                 className={"flex-shrink-0 mt-2 h-6 w-6 md:w-7 md:h-7  " +(openTab === 2
                     ? "text-lightPrimary dark:text-blue-500 "
                     : "text-gray-800 dark:text-gray-200")
                 }
                 xmlns="http://www.w3.org/2000/svg" width={16} height={16} fill="currentColor" viewBox="0 0 16 16">
             <path fillRule="evenodd"
                   d="M0 0h1v15h15v1H0V0Zm14.817 3.113a.5.5 0 0 1 .07.704l-4.5 5.5a.5.5 0 0 1-.74.037L7.06 6.767l-3.656 5.027a.5.5 0 0 1-.808-.588l4-5.5a.5.5 0 0 1 .758-.06l2.609 2.61 4.15-5.073a.5.5 0 0 1 .704-.07Z"/>
             </svg>
             <span className="grow ml-6">
             <span
                 className={"block text-lg font-semibold  "+(openTab === 2
                     ? "text-lightPrimary dark:text-blue-500 "
                     : "text-gray-800 dark:text-gray-200")}>Compliance</span>
             <span className="block mt-1 text-gray-800 dark:hs-tab-active:text-gray-200 dark:text-gray-200">Background background checks
• Due diligence
• Support for compliance</span>
             </span>
             </span>
                                        </button>
                                        <button type="button"
                                                onClick={e => {
                                                    e.preventDefault();
                                                    setOpenTab(3);
                                                }}
                                                className={" text-left " +
                                                    " p-4 md:p-5 rounded-xl  " +
                                                        (openTab === 3
                                                            ? "bg-white shadow-md   dark:bg-slate-900"
                                                            : "hover:bg-gray-200 dark:hover:bg-gray-700")
                                                }
                                                id="tabs-with-card-item-3" data-hs-tab="#tabs-with-card-3"
                                                aria-controls="tabs-with-card-3" role="tab">
             <span className="flex">
             <svg
                 className={"flex-shrink-0 mt-2 h-6 w-6 md:w-7 md:h-7  " +(openTab === 3
                     ? "text-lightPrimary dark:text-blue-500 "
                     : "text-gray-800 dark:text-gray-200")
                 }
                 xmlns="http://www.w3.org/2000/svg" width={16} height={16} fill="currentColor" viewBox="0 0 16 16">
             <path
                 d="M5.52.359A.5.5 0 0 1 6 0h4a.5.5 0 0 1 .474.658L8.694 6H12.5a.5.5 0 0 1 .395.807l-7 9a.5.5 0 0 1-.873-.454L6.823 9.5H3.5a.5.5 0 0 1-.48-.641l2.5-8.5zM6.374 1 4.168 8.5H7.5a.5.5 0 0 1 .478.647L6.78 13.04 11.478 7H8a.5.5 0 0 1-.474-.658L9.306 1H6.374z"/>
             </svg>
             <span className="grow ml-6">
             <span
                 className={"block text-lg font-semibold  "+(openTab === 3
                     ? "text-lightPrimary dark:text-blue-500 "
                     : "text-gray-800 dark:text-gray-200")}>Operationnal</span>

             <span className="block mt-1 text-gray-800 dark:hs-tab-active:text-gray-200 dark:text-gray-200">• Accompaniment anti-corruption
• Export support</span>
             </span>
             </span>
                                        </button>
                                    </nav>
                                    {/* End Tab Navs */}
                                </div>
                                {/* End Col */}
                                <div className="lg:col-span-6">
                                    <div className="relative">
                                        {/* Tab Content */}
                                        <div>
                                            {
                                                (() => {
                                                    switch (openTab) {
                                                        case 1:
                                                            return (
                                                                <div
                                                                    id="tabs-with-card-1"
                                                                    role="tabpanel"
                                                                    aria-labelledby="tabs-with-card-item-1"
                                                                >
                                                                    <Image
                                                                        className="shadow-xl shadow-gray-200 rounded-xl dark:shadow-gray-900/[.2]"
                                                                        src={strategy}
                                                                        alt="Team establishing a strategy"
                                                                        width={987}


                                                                    />
                                                                </div>
                                                            );
                                                        case 2:
                                                            return (
                                                                <div
                                                                    id="tabs-with-card-2"
                                                                    role="tabpanel"
                                                                    aria-labelledby="tabs-with-card-item-2"
                                                                >
                                                                    <Image
                                                                        className="shadow-xl shadow-gray-200 rounded-xl dark:shadow-gray-900/[.2]"
                                                                        src={compliance}
                                                                        alt="Important contract"
                                                                        width={987}
                                                                    />
                                                                </div>
                                                            );
                                                        case 3:
                                                            return (
                                                                <div
                                                                    id="tabs-with-card-3"
                                                                    role="tabpanel"
                                                                    aria-labelledby="tabs-with-card-item-3"
                                                                >
                                                                    <Image
                                                                        className="shadow-xl shadow-gray-200 rounded-xl dark:shadow-gray-900/[.2]"
                                                                        src={operationnal}
                                                                        alt="Woman talking to people"
                                                                        width={987}
                                                                        height={1220}
                                                                    />
                                                                </div>
                                                            );
                                                        default:
                                                            return null;
                                                    }
                                                })()
                                            }
                                        </div>
                                        {/* End Tab Content */}

                                    </div>
                                </div>
                                {/* End Col */}
                            </div>
                            {/* End Grid */}
                            {/* Background Color */}
                            <div className="absolute inset-0 grid grid-cols-12 w-full h-full">
                                <div
                                    className="col-span-full lg:col-span-7 lg:col-start-6 bg-gray-100 w-full h-5/6 rounded-xl sm:h-3/4 lg:h-full dark:bg-white/[.075]"/>
                            </div>
                            {/* End Background Color */}
                        </div>
                    </div>
                    {/* End Features */}
                </section>
                <section>

                    <div className="py-16">
                        <div className="xl:container m-auto px-6 text-gray-600 md:px-12 xl:px-16">
                            <div
                                className="lg:bg-gray-50 dark:lg:bg-darker lg:p-16 rounded-[4rem] space-y-6 md:flex flex-row-reverse md:gap-6 justify-center md:space-y-0 lg:items-center">
                                <div className="md:5/12 lg:w-1/2">
                                    <Image src={professionals} alt={"Team"} className={"rounded-xl"}/>

                                </div>
                                <div className="md:7/12 lg:w-1/2">
                                    <h2 className="text-3xl font-bold text-gray-900 md:text-4xl dark:text-white">
                                        Professionals dedicated to your success
                                    </h2>
                                    <p className="my-8 text-gray-600 dark:text-gray-300">
                                        Our team is skilled, experienced and discreet, allowing us to work closely
                                        with clients to mitigate risks and make informed decisions in challenging
                                        and complex business environments.
                                    </p>
                                    <div className="divide-y space-y-4 divide-gray-100 dark:divide-gray-800">
                                        <div className="mt-8 flex gap-4 md:items-center">
                                            <div
                                                className="w-12 h-12 flex gap-4 rounded-full bg-indigo-100 dark:bg-indigo-900/20">
                                                <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"
                                                     fill="currentColor"
                                                     className="w-6 h-6 m-auto text-indigo-500 dark:text-indigo-400">
                                                    <path fill-rule="evenodd"
                                                          d="M4.848 2.771A49.144 49.144 0 0112 2.25c2.43 0 4.817.178 7.152.52 1.978.292 3.348 2.024 3.348 3.97v6.02c0 1.946-1.37 3.678-3.348 3.97a48.901 48.901 0 01-3.476.383.39.39 0 00-.297.17l-2.755 4.133a.75.75 0 01-1.248 0l-2.755-4.133a.39.39 0 00-.297-.17 48.9 48.9 0 01-3.476-.384c-1.978-.29-3.348-2.024-3.348-3.97V6.741c0-1.946 1.37-3.68 3.348-3.97zM6.75 8.25a.75.75 0 01.75-.75h9a.75.75 0 010 1.5h-9a.75.75 0 01-.75-.75zm.75 2.25a.75.75 0 000 1.5H12a.75.75 0 000-1.5H7.5z"
                                                          clip-rule="evenodd"/>
                                                </svg>
                                            </div>
                                            <div className="w-5/6">
                                                <h4 className="font-semibold text-lg text-gray-700 dark:text-indigo-300">Discreet</h4>
                                                <p className="text-gray-500 dark:text-gray-400">Asperiores nemo possimus
                                                    nesciunt quam mollitia.</p>
                                            </div>
                                        </div>
                                        <div className="pt-4 flex gap-4 md:items-center">
                                            <div
                                                className="w-12 h-12 flex gap-4 rounded-full bg-teal-100 dark:bg-teal-900/20">
                                                <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"
                                                     fill="currentColor"
                                                     className="w-6 h-6 m-auto text-teal-600 dark:text-teal-400">
                                                    <path fill-rule="evenodd"
                                                          d="M11.54 22.351l.07.04.028.016a.76.76 0 00.723 0l.028-.015.071-.041a16.975 16.975 0 001.144-.742 19.58 19.58 0 002.683-2.282c1.944-1.99 3.963-4.98 3.963-8.827a8.25 8.25 0 00-16.5 0c0 3.846 2.02 6.837 3.963 8.827a19.58 19.58 0 002.682 2.282 16.975 16.975 0 001.145.742zM12 13.5a3 3 0 100-6 3 3 0 000 6z"
                                                          clip-rule="evenodd"/>
                                                </svg>
                                            </div>
                                            <div className="w-5/6">
                                                <h4 className="font-semibold text-lg text-gray-700 dark:text-teal-300">Real
                                                    Time Location</h4>
                                                <p className="text-gray-500 dark:text-gray-400">Asperiores nemo possimus
                                                    nesciunt quam mollitia.</p>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </section>
                <section>

                    {/* Contact Us */}
                    <div className="max-w-[85rem] px-4 py-10 sm:px-6 lg:px-8 lg:py-14 mx-auto">
                        <div className="max-w-2xl lg:max-w-5xl mx-auto">
                            <div className="text-center">
                                <h1 className="text-3xl font-bold text-gray-800 sm:text-4xl dark:text-white">
                                    Contact us
                                </h1>
                                <p className="mt-1 text-gray-600 dark:text-gray-400">
                                    We'd love to talk about how we can help you.
                                </p>
                            </div>
                            <div className="mt-12 grid items-center lg:grid-cols-2 gap-6 lg:gap-16">
                                {/* Card */}
                                <div className="flex flex-col border rounded-xl p-4 sm:p-6 lg:p-8 dark:border-gray-700">
                                    <h2 className="mb-8 text-xl font-semibold text-gray-800 dark:text-gray-200">
                                        Fill in the form
                                    </h2>
                                    <form>
                                        <div className="grid gap-4">
                                            {/* Grid */}
                                            <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                                                <div>
                                                    <label htmlFor="hs-firstname-contacts-1" className="sr-only">First
                                                        Name</label>
                                                    <input type="text" name="hs-firstname-contacts-1"
                                                           id="hs-firstname-contacts-1"
                                                           className="py-3 px-4 block w-full border-gray-200 rounded-md text-sm focus:border-blue-500 focus:ring-blue-500 dark:bg-slate-900 dark:border-gray-700 dark:text-gray-400"
                                                           placeholder="First Name"/>
                                                </div>
                                                <div>
                                                    <label htmlFor="hs-lastname-contacts-1" className="sr-only">Last
                                                        Name</label>
                                                    <input type="text" name="hs-lastname-contacts-1"
                                                           id="hs-lastname-contacts-1"
                                                           className="py-3 px-4 block w-full border-gray-200 rounded-md text-sm focus:border-blue-500 focus:ring-blue-500 dark:bg-slate-900 dark:border-gray-700 dark:text-gray-400"
                                                           placeholder="Last Name"/>
                                                </div>
                                            </div>
                                            {/* End Grid */}
                                            <div>
                                                <label htmlFor="hs-email-contacts-1" className="sr-only">Email</label>
                                                <input type="email" name="hs-email-contacts-1" id="hs-email-contacts-1"
                                                       autoComplete="email"
                                                       className="py-3 px-4 block w-full border-gray-200 rounded-md text-sm focus:border-blue-500 focus:ring-blue-500 dark:bg-slate-900 dark:border-gray-700 dark:text-gray-400"
                                                       placeholder="Email"/>
                                            </div>
                                            <div>
                                                <label htmlFor="hs-phone-number-1" className="sr-only">Phone
                                                    Number</label>
                                                <input type="text" name="hs-phone-number-1" id="hs-phone-number-1"
                                                       className="py-3 px-4 block w-full border-gray-200 rounded-md text-sm focus:border-blue-500 focus:ring-blue-500 dark:bg-slate-900 dark:border-gray-700 dark:text-gray-400"
                                                       placeholder="Phone Number"/>
                                            </div>
                                            <div>
                                                <label htmlFor="hs-about-contacts-1" className="sr-only">Details</label>
                                                <textarea id="hs-about-contacts-1" name="hs-about-contacts-1" rows={4}
                                                          className="py-3 px-4 block w-full border-gray-200 rounded-md text-sm focus:border-blue-500 focus:ring-blue-500 dark:bg-slate-900 dark:border-gray-700 dark:text-gray-400"
                                                          placeholder="Details" defaultValue={""}/>
                                            </div>
                                        </div>
                                        {/* End Grid */}
                                        <div className="mt-4 grid">
                                            <button type="submit"
                                                    className="inline-flex justify-center items-center gap-x-3 text-center bg-blue-600 hover:bg-blue-700 border border-transparent text-sm lg:text-base text-white font-medium rounded-md focus:outline-none focus:ring-2 focus:ring-blue-600 focus:ring-offset-2 focus:ring-offset-white transition py-3 px-4 dark:focus:ring-offset-gray-800">Send
                                                inquiry
                                            </button>
                                        </div>
                                        <div className="mt-3 text-center">
                                            <p className="text-sm text-gray-500">
                                                We'll get back to you in 1-2 business days.
                                            </p>
                                        </div>
                                    </form>
                                </div>
                                {/* End Card */}
                                <div className="divide-y divide-gray-200 dark:divide-gray-800">
                                    {/* Icon Block */}
                                    <div className="flex gap-x-7 py-6">
                                        <svg className="flex-shrink-0 w-6 h-6 mt-1.5 text-gray-800 dark:text-gray-200"
                                             xmlns="http://www.w3.org/2000/svg" width={16} height={16}
                                             fill="currentColor" viewBox="0 0 16 16">
                                            <path
                                                d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z"/>
                                            <path
                                                d="M5.255 5.786a.237.237 0 0 0 .241.247h.825c.138 0 .248-.113.266-.25.09-.656.54-1.134 1.342-1.134.686 0 1.314.343 1.314 1.168 0 .635-.374.927-.965 1.371-.673.489-1.206 1.06-1.168 1.987l.003.217a.25.25 0 0 0 .25.246h.811a.25.25 0 0 0 .25-.25v-.105c0-.718.273-.927 1.01-1.486.609-.463 1.244-.977 1.244-2.056 0-1.511-1.276-2.241-2.673-2.241-1.267 0-2.655.59-2.75 2.286zm1.557 5.763c0 .533.425.927 1.01.927.609 0 1.028-.394 1.028-.927 0-.552-.42-.94-1.029-.94-.584 0-1.009.388-1.009.94z"/>
                                        </svg>
                                        <div>
                                            <h3 className="font-semibold text-gray-800 dark:text-gray-200">Knowledgebase</h3>
                                            <p className="mt-1 text-sm text-gray-500">We're here to help with any
                                                questions or code.</p>
                                            <a className="mt-2 inline-flex items-center gap-x-2 text-sm font-medium text-gray-600 hover:text-gray-800 dark:text-gray-400 dark:hover:text-gray-200"
                                               href="#">
                                                Contact support
                                                <svg
                                                    className="w-2.5 h-2.5 transition ease-in-out group-hover:translate-x-1"
                                                    width={16} height={16} viewBox="0 0 16 16" fill="none"
                                                    xmlns="http://www.w3.org/2000/svg">
                                                    <path fillRule="evenodd" clipRule="evenodd"
                                                          d="M0.975821 6.92249C0.43689 6.92249 -3.50468e-07 7.34222 -3.27835e-07 7.85999C-3.05203e-07 8.37775 0.43689 8.79749 0.975821 8.79749L12.7694 8.79748L7.60447 13.7596C7.22339 14.1257 7.22339 14.7193 7.60447 15.0854C7.98555 15.4515 8.60341 15.4515 8.98449 15.0854L15.6427 8.68862C16.1191 8.23098 16.1191 7.48899 15.6427 7.03134L8.98449 0.634573C8.60341 0.268455 7.98555 0.268456 7.60447 0.634573C7.22339 1.00069 7.22339 1.59428 7.60447 1.9604L12.7694 6.92248L0.975821 6.92249Z"
                                                          fill="currentColor"/>
                                                </svg>
                                            </a>
                                        </div>
                                    </div>
                                    {/* End Icon Block */}
                                    {/* Icon Block */}
                                    <div className="flex gap-x-7 py-6">
                                        <svg className="flex-shrink-0 w-6 h-6 mt-1.5 text-gray-800 dark:text-gray-200"
                                             xmlns="http://www.w3.org/2000/svg" width={16} height={16}
                                             fill="currentColor" viewBox="0 0 16 16">
                                            <path
                                                d="M14 1a1 1 0 0 1 1 1v8a1 1 0 0 1-1 1H4.414A2 2 0 0 0 3 11.586l-2 2V2a1 1 0 0 1 1-1h12zM2 0a2 2 0 0 0-2 2v12.793a.5.5 0 0 0 .854.353l2.853-2.853A1 1 0 0 1 4.414 12H14a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2H2z"/>
                                            <path
                                                d="M5 6a1 1 0 1 1-2 0 1 1 0 0 1 2 0zm4 0a1 1 0 1 1-2 0 1 1 0 0 1 2 0zm4 0a1 1 0 1 1-2 0 1 1 0 0 1 2 0z"/>
                                        </svg>
                                        <div>
                                            <h3 className="font-semibold text-gray-800 dark:text-gray-200">FAQ</h3>
                                            <p className="mt-1 text-sm text-gray-500">Search our FAQ for answers to
                                                anything you might ask.</p>
                                            <a className="mt-2 inline-flex items-center gap-x-2 text-sm font-medium text-gray-600 hover:text-gray-800 dark:text-gray-400 dark:hover:text-gray-200"
                                               href="#">
                                                Visit FAQ
                                                <svg
                                                    className="w-2.5 h-2.5 transition ease-in-out group-hover:translate-x-1"
                                                    width={16} height={16} viewBox="0 0 16 16" fill="none"
                                                    xmlns="http://www.w3.org/2000/svg">
                                                    <path fillRule="evenodd" clipRule="evenodd"
                                                          d="M0.975821 6.92249C0.43689 6.92249 -3.50468e-07 7.34222 -3.27835e-07 7.85999C-3.05203e-07 8.37775 0.43689 8.79749 0.975821 8.79749L12.7694 8.79748L7.60447 13.7596C7.22339 14.1257 7.22339 14.7193 7.60447 15.0854C7.98555 15.4515 8.60341 15.4515 8.98449 15.0854L15.6427 8.68862C16.1191 8.23098 16.1191 7.48899 15.6427 7.03134L8.98449 0.634573C8.60341 0.268455 7.98555 0.268456 7.60447 0.634573C7.22339 1.00069 7.22339 1.59428 7.60447 1.9604L12.7694 6.92248L0.975821 6.92249Z"
                                                          fill="currentColor"/>
                                                </svg>
                                            </a>
                                        </div>
                                    </div>
                                    {/* End Icon Block */}
                                    {/* Icon Block */}
                                    <div className=" flex gap-x-7 py-6">
                                        <svg className="flex-shrink-0 w-6 h-6 mt-1.5 text-gray-800 dark:text-gray-200"
                                             xmlns="http://www.w3.org/2000/svg" width={16} height={16}
                                             fill="currentColor" viewBox="0 0 16 16">
                                            <path
                                                d="M6 9a.5.5 0 0 1 .5-.5h3a.5.5 0 0 1 0 1h-3A.5.5 0 0 1 6 9zM3.854 4.146a.5.5 0 1 0-.708.708L4.793 6.5 3.146 8.146a.5.5 0 1 0 .708.708l2-2a.5.5 0 0 0 0-.708l-2-2z"/>
                                            <path
                                                d="M2 1a2 2 0 0 0-2 2v10a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V3a2 2 0 0 0-2-2H2zm12 1a1 1 0 0 1 1 1v10a1 1 0 0 1-1 1H2a1 1 0 0 1-1-1V3a1 1 0 0 1 1-1h12z"/>
                                        </svg>
                                        <div>
                                            <h3 className="font-semibold text-gray-800 dark:text-gray-200">Developer
                                                APIs</h3>
                                            <p className="mt-1 text-sm text-gray-500">Check out our development
                                                quickstart guide.</p>
                                            <a className="mt-2 inline-flex items-center gap-x-2 text-sm font-medium text-gray-600 hover:text-gray-800 dark:text-gray-400 dark:hover:text-gray-200"
                                               href="#">
                                                Contact sales
                                                <svg
                                                    className="w-2.5 h-2.5 transition ease-in-out group-hover:translate-x-1"
                                                    width={16} height={16} viewBox="0 0 16 16" fill="none"
                                                    xmlns="http://www.w3.org/2000/svg">
                                                    <path fillRule="evenodd" clipRule="evenodd"
                                                          d="M0.975821 6.92249C0.43689 6.92249 -3.50468e-07 7.34222 -3.27835e-07 7.85999C-3.05203e-07 8.37775 0.43689 8.79749 0.975821 8.79749L12.7694 8.79748L7.60447 13.7596C7.22339 14.1257 7.22339 14.7193 7.60447 15.0854C7.98555 15.4515 8.60341 15.4515 8.98449 15.0854L15.6427 8.68862C16.1191 8.23098 16.1191 7.48899 15.6427 7.03134L8.98449 0.634573C8.60341 0.268455 7.98555 0.268456 7.60447 0.634573C7.22339 1.00069 7.22339 1.59428 7.60447 1.9604L12.7694 6.92248L0.975821 6.92249Z"
                                                          fill="currentColor"/>
                                                </svg>
                                            </a>
                                        </div>
                                    </div>
                                    {/* End Icon Block */}
                                    {/* Icon Block */}
                                    <div className=" flex gap-x-7 py-6">
                                        <svg className="flex-shrink-0 w-6 h-6 mt-1.5 text-gray-800 dark:text-gray-200"
                                             xmlns="http://www.w3.org/2000/svg" width={16} height={16}
                                             fill="currentColor" viewBox="0 0 16 16">
                                            <path
                                                d="M0 4a2 2 0 0 1 2-2h12a2 2 0 0 1 2 2v8a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2V4Zm2-1a1 1 0 0 0-1 1v.217l7 4.2 7-4.2V4a1 1 0 0 0-1-1H2Zm13 2.383-4.708 2.825L15 11.105V5.383Zm-.034 6.876-5.64-3.471L8 9.583l-1.326-.795-5.64 3.47A1 1 0 0 0 2 13h12a1 1 0 0 0 .966-.741ZM1 11.105l4.708-2.897L1 5.383v5.722Z"/>
                                        </svg>
                                        <div>
                                            <h3 className="font-semibold text-gray-800 dark:text-gray-200">Contact us by
                                                email</h3>
                                            <p className="mt-1 text-sm text-gray-500">If you wish to write us an email
                                                instead please use</p>
                                            <a className="mt-2 inline-flex items-center gap-x-2 text-sm font-medium text-gray-600 hover:text-gray-800 dark:text-gray-400 dark:hover:text-gray-200"
                                               href="#">
                                                example@site.com
                                            </a>
                                        </div>
                                    </div>
                                    {/* End Icon Block */}
                                </div>
                            </div>
                        </div>
                    </div>
                    {/* End Contact Us */}

                </section>
            </main>
        </>
    )
}
